name: dva_dart
description: Dart library porting from dvajs, a great combination of redux,redux_saga, a simpler way to manage your app's state.
version: 0.0.1
author: neeboo <neeboo@firestack>
homepage: https://github.com/neeboo/dva_dart

environment:
  sdk: '>=1.8.0 <3.0.0'

dependencies:
  meta: '^1.1.6'
  redux: ^3.0.0

dev_dependencies:
  test: ^1.3.2
