name: dva_dart
description: State manager for dart and flutter, using idea from dva.js and combined with rxdart, a simpler way to manage your app's state.
version: 0.0.6
author: neeboo <neeboo@firestack>
homepage: https://github.com/neeboo/dva_dart

environment:
  sdk: '>=1.8.0 <3.0.0'

dependencies:
  meta: '^1.1.6'
  rxdart: '^0.20.0'

dev_dependencies:
  test: ^1.3.2
